language: node_js

node_js:
  - 6.1.0

install:
  - npm install -g codecov
  - npm install -g istanbul

services:
  - redis
  - mysql

addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

script:
  - npm install
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - codecov

after_success: npm i codecov && codecov

branches:
  only:
    - master
